apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: muchtodo
spec:
  accessModes:
    - ReadWriteOnce       # One node can mount at a time (fine for single MongoDB pod)
  resources:
    requests:
      storage: 1Gi        # 1GB is enough for local Kind cluster
