apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: muchtodo
data:
  # Internal service name — backend uses this as the hostname
  mongo-host: "mongodb-service"
  mongo-port: "27017"
