apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
# Values are base64 encoded
# To encode:  echo -n 'yourvalue' | base64
# root        → cm9vdA==
# rootpassword → cm9vdHBhc3N3b3Jk
# much_todo_db → bXVjaF90b2RvX2Ri
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cm9vdHBhc3N3b3Jk
  mongo-database: bXVjaF90b2RvX2Ri
